dataset:
  use_cache: False
  shuffle: False
  buffer_size: 100


tokenizer: 
  type: "sentencepiece"
  vocab_size: 10000

  
feature_extractor:
  sampling_rate: 16000
  frame_ms: 25
  hop_ms: 10
  center: True
  window_type: "hanning"
  preemphasis_coeff: 0.97
  top_db: 80.0
  num_mel_bins: 80
  num_mfcc_bins: 40
  min_hertz: 0
  max_hertz: 8000
  feature_type: "logmel"
  normalize_signal: True
  normalize_feature: True
  epsilon: 1e-10


spec_augment:
  time_masks_number: 2
  time_mask_max_size: 10
  frequency_masks_number: 2
  frequency_mask_max_size: 5

model:
  model_type: "TDS"
  
  params:
    encoder_kernel_size: 21
    encoder_num_tds_blocks: [3, 6, 5]
    encoder_num_tds_channels: [10, 14, 18]
    encoder_dropout_prob: 0.1

    decoder_num_units: 1024
    decoder_attention_type: scaled_dot
    decoder_attention_dim: 1024
    
  
training:
  batch_per_device: 32
  epochs: 100
  
  init_lr: 0.05
  lr_decay_rate: 0.5
  lr_decay_step: 40
  optimizer: "sgd"
  #optimizer: "adam"
  #global_clipnorm: 15.0
  clipnorm: 15.0